//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Password_Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Password_Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aiuto.
        /// </summary>
        internal static string AiutoMenuItem {
            get {
                return ResourceManager.GetString("AiutoMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Genera Password .
        /// </summary>
        internal static string btnGeneraPassword {
            get {
                return ResourceManager.GetString("btnGeneraPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva Password.
        /// </summary>
        internal static string btnSalvaPassword {
            get {
                return ResourceManager.GetString("btnSalvaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generatore Password creato da Andrea Antonio Perrelli. 
        ///Controlla il repository https://github.com/AndreaPerrelli/Password-Generator per ulteriori aggiornamenti..
        /// </summary>
        internal static string Informazioni {
            get {
                return ResourceManager.GetString("Informazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni.
        /// </summary>
        internal static string InformazioniMenuItem {
            get {
                return ResourceManager.GetString("InformazioniMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome Sito .
        /// </summary>
        internal static string lblNomeSito {
            get {
                return ResourceManager.GetString("lblNomeSito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome Utente/Email .
        /// </summary>
        internal static string lblNomeUtente {
            get {
                return ResourceManager.GetString("lblNomeUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password Ottenuta.
        /// </summary>
        internal static string lblPasswordOttenuta {
            get {
                return ResourceManager.GetString("lblPasswordOttenuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a password salvata con successo, path : .
        /// </summary>
        internal static string salvataggioPassword {
            get {
                return ResourceManager.GetString("salvataggioPassword", resourceCulture);
            }
        }
    }
}
